config/routes.rb
Rails.application.routes.draw do
  # resources :users
resources :students
root 'pages#home'
get 'about',to: 'pages#about'
get 'signup',to:"courses#new"
resources :courses,except: [:new]
get 'login',to:'sessions#new'
post 'login',to:'sessions#create'
delete 'logout',to:'sessions#destroy'
resources :categories,except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name,presence:true,length: { minimum:3, maximum:25 } 
    validates_uniqueness_of :name
    has_many :student_categories
    has_many :students,through: :student_categories
end   

app/models/course.rb
class Course < ApplicationRecord
    before_save {self.email=email.downcase}
    validates:username,presence:true,uniqueness: { case_sensitive: false},length:{minimum:3,maximum:25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates:email,presence:true,uniqueness: { case_sensitive: false},length:{maximum:105},format:{with:VALID_EMAIL_REGEX}
    has_many :students,dependent: :destroy
    has_secure_password
    
end

app/models/student.rb
class Student < ApplicationRecord
    validates :firstname, presence: true ,length: {minimum:2, maximum:10}
    validates :roll, presence: true ,length: {minimum:3, maximum:3}
    belongs_to :course
    has_many :student_categories
    has_many :categories,through: :student_categories

end

app/models/student_category.rb
class StudentCategory < ApplicationRecord
    belongs_to :student
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

    end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin,except: [:index,:show]
    def index
        @category=Category.all
    end
    def new
        @category=Category.new()
    end
    def show
        @category=Category.find(params[:id])
        # @category_students=@category.students
    end
    def create
        @category=Category.new(params.require(:category).permit(:name))
       if @category.save
        redirect_to categories_path()
       else
        render 'new'
       end
    end
    def edit
        @category=Category.find(params[:id])
    end
    def update
        @category=Category.find(params[:id])
        if @category.update(params.require(:category).permit(:name))
            redirect_to category_path(@category)
        else
            render 'edit'
    end
end
private 
 def require_admin
 if !logged_in? || (logged_in? && !current_user.admin?)
    redirect_to login_path()
 
 end
 end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action:req_same_user,except: [:new,:create,:show,:index,:destroy]
    before_action:req_admin,only: [:destroy]
    def new
        @course=Course.new
    end
    def create
    @course=Course.new(course_params)
    if  @course.save
        session[:course_id]=@course.id
        redirect_to course_path(@course.id)

    else
        render 'new'
    end    
    end
    def index
        @course=Course.paginate(page: params[:page],per_page: 5)
    end
    def edit
        @course=Course.find(params[:id])
    end
    def update
    @course=Course.find(params[:id])
    if  @course.update(course_params) 
    redirect_to @course
    else 
        render 'edit'
    end
    end
    def show
    @course=Course.find(params[:id])
    @student=@course.students.paginate(page: params[:page],per_page: 5)
    end
    def destroy
    @course=Course.find(params[:id])
    @course.destroy
    redirect_to courses_path()
    end
    private
    def course_params
    params.require(:course).permit(:username,:email,:password)
    end
    def req_same_user
    if !logged_in? || (current_user != @course&& current_user.admin?)
        redirect_to courses_path()
    end
    end
    def req_admin
    if logged_in? && !current_user.admin?
        redirect_to root_path()
    end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
    def home
    #     p "-----------------------------------"
        p logged_in?
    #     p "---------------------------------"
       redirect_to students_path() if logged_in?
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    def create
        user=Course.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:course_id]=user.id
        redirect_to user
        else
            flash.now[:alert]="Something wrong with credentials"
        render 'new'
        end
    end
    def destroy
        session[:course_id]=nil
        redirect_to root_path
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    # include ApplicationHelper
before_action:set_articles, only: [:show,:destroy,:edit,:update]
before_action:req_user, except: [:index,:show]
before_action:same_user,only: [:edit,:update,:destroy]
    def show
        
    end
    def index
       
        @student=Student.paginate(page: params[:page],per_page: 5)
        # @course=@student.course
    end
    def new
        @student=Student.new
    end

    def create
        @student=Student.new(set_params)
        @student.course=current_user
        # render plain: student.inspect
        if @student.save
            redirect_to @student
        else
        render 'new'
        end
    end
    def edit
        
    end
    def update
    
    student=@student.update(set_params)
    redirect_to @student
      end
     def destroy
       
        @student.destroy
        redirect_to students_path
     end
     private
     def set_articles
        @student=Student.find(params[:id])
     end
     def set_params
        params.require(:student).permit(:firstname, :roll,category_ids:[])
    end
    def same_user
        if current_user != @student.course and !current_user.admin?
            redirect_to root_path()
    end 
end

end 
 

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
  
    def current_user
      @current_user ||= Course.find(session[:course_id]) if session[:course_id]
    end
  
    def logged_in?
      !!current_user
    end
    def req_user
    
        if !logged_in?
        redirect_to root_path()
        end
    end
    
  end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<%=link_to category.name,category_path(category) %> &nbsp;

app/views/categories/edit.html.erb
<%=form_with(model:@category,local:true) do |t|%>
    <br>
<%=t.label :name%><br><br>
<%=t.text_field :name%><br>
<br>
<%=t.submit%>
<%end%>

app/views/categories/index.html.erb
<p>Categories Index</p>
<% @category.each do |t| %>
    <%=link_to t.name,category_path(t.id)%> 
    <%=t.students.count%><br>
    
    <%end%>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%=form_with(scope: :category,url:categories_url,local: true) do |t|%>
    <p><%=t.label :name%>
    <%=t.text_field :name%></p>
    <p><%=t.submit("Save")%></p>
<%end%>

app/views/categories/show.html.erb
<p>Category</p>
<%=@category.name %>
<%if @category.students.any?%>
<%=render @category.students%>
<%end%>

app/views/courses/_form.html.erb
<%if @course.errors.any? %>
<h2>Not signed in</h2>
<ul><% @course.errors.full_messages.each do |t| %>
     <li> <%=t%></li>               
      <%end%>
<%end%>
<%=form_with(model: @course,local: true) do |t|%>
        
    <p> <%=  t.label :username%>
   <%= t.text_field :username%></p>
  <p> <%= t.label :email%>
    <%=t.email_field :email%></p>
    <p> <%= t.label :password%>
    <%=t.password_field :password%></p>
    <p><%=t.submit(@course.new_record? ? ("Signup") : ("UpdateAccount"))%></p>
    <%end%>
        

app/views/courses/edit.html.erb
<h1>Edit users</h1>
<%= render 'form' %>

app/views/courses/index.html.erb
<div class="flickr_pagination">
<%= will_paginate @course %>
<% @course.each do |t|%>
<%=link_to t.username,course_path(t.id) %>
<%=t.students.count%><br>
<% if logged_in? && current_user.admin? %>
<%=link_to 'delete_user',course_path(t.id),method: :delete%>
<%end%>
<%end%>
<div class="flickr_pagination">
<%= will_paginate @course%>

app/views/courses/new.html.erb
<h1>New user</h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<h1><%=@course.username%>'s profile</h1>
<%=gravatar_for @course, size:200%>
<h3>Students</h3>
<div class="flickr_pagination">
<%= will_paginate @student %>
<% @student.each do |t| %>
    <p><%=link_to t.firstname,student_path(t.id)%></p>
    <p><%=@course.students.count%></p><br>
    
    <% if logged_in? && current_user == @course%>
 


<p><%=link_to "EdityourProfile",edit_course_path(@course)%></p>
<p><%=link_to "logout",logout_path,method: :delete%></p>
<%end%>
<%end%>
<div class="flickr_pagination">
<%= will_paginate @student %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
      <%= link_to current_user.username, course_path(current_user), class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'New Student', new_student_path(), class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'New Category', new_category_path(), class: "nav-link"%>
    </li>
      <li class="nav-item">
      <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
       <%else%>
       </li>
       <li class="nav-item">
      <%= link_to 'Login', login_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign Up', signup_path, class: "nav-link"%>
    </li>
    <%end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>Check the students page</h2>
<%= link_to 'new',new_student_path()%>
<%= link_to 'Return to home',root_path%>
<%= link_to 'Articles index',students_path()%>

app/views/pages/home.html.erb
<h1>Welcome to students page</h1>
<%=link_to 'about',about_path%>
<%=link_to 'Go to articles index',students_path()%>
<%=link_to 'Signup for new course',signup_path()%>

app/views/students/_form.html.erb
<%if @student.errors.any? %>
<h2>User not edited due to</h2>
<ul><% @student.errors.full_messages.each do |t| %>
     <li> <%=t%></li>               
      <%end%>
<%end%>
<%=form_with(model: @student,local: true) do |t|%>
        
    <p> <%=  t.label :firstname%>
   <%= t.text_field :firstname%></p>
  <p> <%= t.label :roll%>
    <%=t.text_field :roll%></p>
    <%=t.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>

      <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %> 
  <%end%>
    <p><%=t.submit("Saveedit")%></p>
    <%end%>
        

app/views/students/_student.html.erb
<%=link_to student.firstname ,student_path(student)%>&nbsp; 

app/views/students/edit.html.erb
<h1>Ready to edit</h1>

    <%=render 'form'%>
    <%=link_to 'return_to_index',students_path%>

app/views/students/index.html.erb
<h1>List of Students</h1>
<div class="flickr_pagination">
<%= will_paginate @student %>
</div>
<table>
<thead>
<tr>
<th>Firstname</th>
<th>Roll</th>
<th colspan=3>Action</th>
</tr>
</thead>
<body>
   <% @student.each do |t|%>
<tr> <td><%=t.firstname%></td>
 <td><%=t.roll%></td>

 <td><%=link_to 'show',student_path(t.id)%></td>
 <td><p>Categories<%=render t.categories %></td></p>
 <% if logged_in? && (current_user == t.course || current_user.admin?)%>
 <td><%=link_to 'delete',student_path(t.id),method: :delete%></td>
 <td><%=link_to 'edit',edit_student_path(t.id)%></td></tr><br>
 <%end%> 
<%end%>

</body>
</table>
<p><%=link_to 'new',new_student_path%></p>
<div class="flickr_pagination">
<%= will_paginate @student %>
</div>

app/views/students/new.html.erb
<h1>New user</h1>
<%= render 'form' %>

app/views/students/show.html.erb
<h1>Student details</h1>
<p>First name is <i><%= @student.firstname %></i></p>
<p>Roll is <%= @student.roll %></p>
<% if @student.categories.any? %>
<p> Categories <%= render @student.categories  %></p>
<%end%> 
<%if logged_in? && (current_user==@student.course || current_user.admin?)%>
<%= link_to @student.course.username,course_path(@student.course) %>
<%= link_to 'edit',edit_student_path(@student.id)%>
<%= link_to 'delete',student_path(@student.id),method: :delete,data: {confirm:"Are you sure?"}%>
<%end%>
<%= link_to 'return to index',students_path()%>         

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>